app/routes/forest.py
from flask import Blueprint, flash, redirect, render_template, request, url_for
from flask_login import current_user, login_required
from werkzeug.utils import secure_filename
import os
from app import Config 
from app.models import Forest
from app.utils.district_utils import get_all_districts
from app.utils.forest_utils import create_forest, delete_forest, get_all_forests, update_forest
from app.utils.point_utils import get_all_points

bp = Blueprint('forest', __name__)


def forest_or_admin_required(f):
    @login_required
    def wrap(*args, **kwargs):
        if current_user.user_type != 'forest' and not current_user.is_admin:
            flash('You do not have permission to access this page.', 'danger')
            return redirect(url_for('main.home'))
        return f(*args, **kwargs)
    wrap.__name__ = f.__name__
    return wrap

@bp.route('/forest')
@forest_or_admin_required
def index():
    page = request.args.get('page', 1, type=int)
    
    if current_user.is_admin:
        forests = Forest.query.paginate(page=page, per_page=6)
    else:
        forests = Forest.query.filter_by(created_by=current_user.id).paginate(page=page, per_page=6)

    points = get_all_points()
    districts = get_all_districts()
    owner_types = ['Farmer', 'Forest', 'Both']
    
    return render_template('forest/forest.html', forests=forests, points=points, districts=districts, owner_types=owner_types)

def allowed_file(filename):
    return '.' in filename and filename.rsplit('.', 1)[1].lower() in Config.ALLOWED_EXTENSIONS

@bp.route('/forest/create', methods=['POST'])
@forest_or_admin_required
def handle_create_forest():
    if request.method == 'POST':
        name = request.form.get('name')
        tree_type = request.form.get('tree_type')
        
        if 'image' in request.files:
            file = request.files['image']
        
            if file.filename != '':
                if not allowed_file(file.filename):
                    flash('Invalid file format. Allowed formats are png, jpg, jpeg, gif', 'danger')
                    return redirect(request.url)
                
                filename = secure_filename(file.filename)
                os.makedirs(Config.UPLOAD_FOLDER, exist_ok=True)  # Create the UPLOAD_FOLDER if it doesn't exist
                file.save(os.path.join(Config.UPLOAD_FOLDER, filename))
            else:
                filename = None
        else:
            filename = None

        create_forest(name, tree_type)
        print('Forest created successfully', 'success')
        return redirect(url_for('forest.index'))
    
    return redirect(url_for('forest.index'))

@bp.route('/forest/update/<int:id>', methods=['POST'])
@forest_or_admin_required
def handle_update_forest(id):
    name = request.form['name']
    tree_type = request.form['tree_type']
    update_forest(id, name, tree_type)
    return redirect(url_for('forest.index'))

@bp.route('/forest/delete/<int:id>', methods=['POST'])
@forest_or_admin_required
def handle_delete_forest(id):
    delete_forest(id)
    return redirect(url_for('forest.index'))

@bp.route('/forest/view')
@forest_or_admin_required
def view():
    forests = get_all_forests()
    points = get_all_points()
    return render_template('forest/forest.html', forests=forests, points=points)

app/routes/point.py
import pandas as pd
import os
from flask import Blueprint, jsonify, render_template, request, redirect, url_for, flash
from flask_login import current_user, login_required
from app.models import District, Farm, Forest, Point
from app.routes.admin import admin_required
from app.routes.farm import farmer_or_admin_required
from app import db
from app.utils.point_utils import create_point, delete_point, get_all_points, get_point_by_id, update_point
from werkzeug.utils import secure_filename
from app import Config 

bp = Blueprint('points', __name__)

@bp.route('/points', methods=['GET'])
@login_required
def list_points():
    page = request.args.get('page', 1, type=int)
    
    # Check if the user is an admin
    if current_user.is_admin:
        points = Point.query.paginate(page=page, per_page=6)
    else:
        points = Point.query.filter_by(created_by=current_user.id).paginate(page=page, per_page=6)
    
    return render_template('points/list.html', points=points)

@bp.route('/points/<int:point_id>', methods=['GET'])
@login_required
def view_point(point_id):
    point = get_point_by_id(point_id)
    if not point:
        flash('Point not found.', 'error')
        return redirect(url_for('points.list_points'))
    return render_template('points/view.html', point=point)

@bp.route('/points/create', methods=['GET', 'POST'])
@login_required
def create_point_route():
    if request.method == 'POST':
        longitude = request.form.get('longitude')
        latitude = request.form.get('latitude')
        owner_type = request.form.get('owner_type')
        forest_id = request.form.get('forest_id')
        farmer_id = request.form.get('farmer_id')
        district_id = request.form.get('district_id')
        print(district_id)

        # Validate required fields
        if not longitude or not latitude or not owner_type:
            flash('Longitude, latitude, and owner type are required.', 'error')
            return render_template('points/create.html')

        # Validate and process forest_id and farmer_id based on owner_type
        if owner_type == 'forest':
            if forest_id:
                forest_id = int(forest_id)
                forest = Forest.query.get(forest_id)
                if not forest:
                    flash('Invalid Forest ID.', 'error')
                    return render_template('points/create.html')
            else:
                forest_id = None
            farmer_id = None
        elif owner_type == 'farmer':
            farmer_id = farmer_id if farmer_id else None
            forest_id = None
        else:
            flash('Invalid owner type.', 'error')
            return render_template('points/create.html')

        try:
            create_point(longitude, latitude, owner_type, district_id, forest_id, farmer_id)
            flash('Point created successfully!', 'success')
        except Exception as e:
            db.session.rollback()
            flash(f'Error creating point: {e}', 'error')

        return redirect(url_for('points.list_points'))
    
    districts = District.query.all()
    if current_user.is_admin :
        farms = Farm.query.all()
        forests = Forest.query.all()
    else :
        farms = Farm.query.filter_by(created_by=current_user.id)
        forests = Forest.query.filter_by(created_by=current_user.id)

    return render_template('points/create.html', districts=districts, forests=forests, farms=farms)
@bp.route('/points/edit/<int:point_id>', methods=['GET', 'POST'])
@login_required
def edit_point_route(point_id):
    point = get_point_by_id(point_id)
    if not point:
        flash('Point not found.', 'error')
        return redirect(url_for('points.list_points'))

    if request.method == 'POST':
        longitude = request.form.get('longitude')
        latitude = request.form.get('latitude')
        owner_type = request.form.get('owner_type')
        forest_id = request.form.get('forest_id')
        farmer_id = request.form.get('farmer_id')
        district_id = request.form.get('district_id')

        # Validate required fields
        if not longitude or not latitude or not owner_type:
            flash('Longitude, latitude, and owner type are required.', 'error')
            return render_template('points/edit.html', point=point)

        # Validate and process forest_id and farmer_id based on owner_type
        if owner_type == 'forest':
            if forest_id:
                forest_id = int(forest_id)
                forest = Forest.query.get(forest_id)
                if not forest:
                    flash('Invalid Forest ID.', 'error')
                    return render_template('points/edit.html', point=point)
            else:
                flash('Forest ID is required for owner type "forest".', 'error')
                return render_template('points/edit.html', point=point)
            farmer_id = None
        elif owner_type == 'farmer':
            if farmer_id:
                farmer_id = farmer_id
                farmer = Farm.query.filter_by(farm_id=farmer_id).first()
                if not farmer:
                    flash('Invalid Farmer ID.', 'error')
                    return render_template('points/edit.html', point=point)
            else:
                flash('Farmer ID is required for owner type "farmer".', 'error')
                return render_template('points/edit.html', point=point)
            forest_id = None
        else:
            flash('Invalid owner type.', 'error')
            return render_template('points/edit.html', point=point)

        try:
            update_point(point_id, longitude, latitude, owner_type, district_id, forest_id, farmer_id)
            flash('Point updated successfully!', 'success')
        except Exception as e:
            db.session.rollback()
            flash(f'Error updating point: {e}', 'error')

        return redirect(url_for('points.list_points'))

    districts = District.query.all()
    if current_user.is_admin:
        farms = Farm.query.all()
        forests = Forest.query.all()
    else:
        farms = Farm.query.filter_by(created_by=current_user.id)
        forests = Forest.query.filter_by(created_by=current_user.id)
    return render_template('points/edit.html', point=point, districts=districts, forests=forests, farms=farms)

@bp.route('/points/delete/<int:point_id>', methods=['POST'])
@login_required
def delete_point_route(point_id):
    try:
        delete_point(point_id)
        flash('Point deleted successfully!', 'success')
    except Exception as e:
        db.session.rollback()
        flash(f'Error deleting point: {e}', 'error')
    
    return redirect(url_for('points.list_points'))

def validate_csv_columns(file_path, required_columns):
    data = pd.read_csv(file_path)
    missing_columns = [col for col in required_columns if col not in data.columns]
    return missing_columns

@bp.route('/points/upload', methods=['GET', 'POST'])
@login_required
def upload_points_route():
    if request.method == 'POST':
        file = request.files.get('file')
        if file and file.filename.endswith('.csv'):
            # Ensure the uploads directory exists
            upload_folder = Config.UPLOAD_FOLDER
            if not os.path.exists(upload_folder):
                os.makedirs(upload_folder)

            # Save the file
            filename = secure_filename(file.filename)
            file_path = os.path.join(upload_folder, filename)
            file.save(file_path)

            # Validate the CSV columns
            required_columns = ['longitude', 'latitude', 'owner_type', 'forest_id', 'farmer_id', 'district_id']
            missing_columns = validate_csv_columns(file_path, required_columns)

            if missing_columns:
                flash(f'Missing required columns: {", ".join(missing_columns)}', 'error')
                return render_template('points/upload.html')

            # Read and process the CSV data
            data = pd.read_csv(file_path)
            for index, row in data.iterrows():
                try:
                    point = Point(
                        longitude=row['longitude'],
                        latitude=row['latitude'],
                        owner_type=row['owner_type'],
                        forest_id=row['forest_id'] if not pd.isna(row['forest_id']) else None,
                        farmer_id=row['farmer_id'] if not pd.isna(row['farmer_id']) else None,
                        district_id=row['district_id']
                    )
                    db.session.add(point)
                except Exception as e:
                    flash(f'Error processing row {index}: {e}', 'error')
            try:
                db.session.commit()
                flash('Points uploaded and created successfully!', 'success')
            except Exception as e:
                db.session.rollback()
                flash(f'Error uploading points: {e}', 'error')
        else:
            flash('Invalid file format. Please upload a CSV file.', 'error')
    
    return render_template('points/upload.html')

app/routes/tree.py
from flask import Blueprint, flash, redirect, render_template, request, send_file, url_for
from flask_login import current_user, login_required
from app import db
from app.models import Forest, Tree
from app.routes.forest import forest_or_admin_required
from app.utils.qr_generator import generate_qr_codes_dynamic
from app.utils.tree_utils import create_tree, delete_tree, get_all_tree, get_tree_by_id, update_tree

bp = Blueprint('tree', __name__)

@bp.route('/trees', methods=['GET'])
@login_required
@forest_or_admin_required
def list_trees():
    trees = get_all_tree()
    return render_template('tree/list.html', trees=trees)

@bp.route('/tree/<int:tree_id>', methods=['GET'])
@login_required
@forest_or_admin_required
def view_tree(tree_id):
    tree = get_tree_by_id(tree_id)
    return render_template('tree/view.html', tree=tree)

@bp.route('/trees/create', methods=['GET', 'POST'])
@login_required
@forest_or_admin_required
def create_tree_route():
    if request.method == 'POST':
        name = request.form.get('name')
        type = request.form.get('type')
        forest_id = request.form.get('forest_id')
        point_id = request.form.get('point_id')
        date_planted = request.form.get('date_planted')
        cutting_date = request.form.get('cutting_date')
        height = request.form.get('height')
        diameter = request.form.get('diameter')
        created_by = current_user.id  # Assuming you have current_user

        create_tree(name, type, forest_id, point_id, date_planted, cutting_date, height, diameter, created_by)
        flash('Tree created successfully.', 'success')
        return redirect(url_for('tree.list_trees'))
    return render_template('tree/create.html')

@bp.route('/tree/edit/<int:tree_id>', methods=['GET', 'POST'])
@login_required
@forest_or_admin_required
def edit_tree_route(tree_id):
    tree = get_tree_by_id(tree_id)
    if request.method == 'POST':
        name = request.form.get('name')
        type = request.form.get('type')
        forest_id = request.form.get('forest_id')
        point_id = request.form.get('point_id')
        date_planted = request.form.get('date_planted')
        cutting_date = request.form.get('cutting_date')
        height = request.form.get('height')
        diameter = request.form.get('diameter')
        modified_by = current_user.id  # Assuming you have current_user

        update_tree(tree_id, name, type, forest_id, point_id, date_planted, cutting_date, height, diameter, modified_by)
        flash('Tree updated successfully.', 'success')
        return redirect(url_for('tree.list_trees'))
    return render_template('tree/edit.html', tree=tree)

@bp.route('/tree/delete/<int:tree_id>', methods=['POST'])
@login_required
@forest_or_admin_required
def delete_tree_route(tree_id):
    delete_tree(tree_id)
    flash('Tree deleted successfully.', 'success')
    return redirect(url_for('tree.list_trees'))

@bp.route('/tree/qr/<int:tree_id>', methods=['GET'])
@login_required
@forest_or_admin_required
def qr_tree_route(tree_id):
    tree = get_tree_by_id(tree_id)
    if tree is None:
        flash('Tree not found.', 'error')
        return redirect(url_for('tree.list_trees'))

    data = f"Forest ID: {tree.forest_id}\nTree ID: {tree.id}\nType: {tree.type}\nCutting Date: {tree.date_cut}\nHeight: {tree.height}\nDiameter: {tree.diameter}"
    pdf_filename = f"tree_{tree.id}_qr_code.pdf"
    qr_pdf_path = generate_qr_codes_dynamic(data, pdf_filename)

    return send_file(qr_pdf_path, as_attachment=True, download_name=pdf_filename, mimetype='application/pdf')

app/templates/forest/forest.html
{% extends 'layout.html' %}

{% block title %}
    Forest and Point Management
{% endblock %}

{% block content %}
<div class="container mx-auto px-4 py-8">
    <h1 class="text-3xl font-bold mb-6 text-center">Forest and Point Management</h1>
    <div class="flex justify-center mb-6">
        <a href="{{ url_for('map.get_all_forests_geojson') }}" class="text-blue-500 hover:underline mb-4 inline-block px-4 py-2 rounded">View All Forests on Map</a>
                <a href="{{ url_for('points.create_point_route') }}" class="text-blue-500 hover:underline mb-4 inline-block px-4 py-2 rounded">Create Point</a>
        <a href="{{ url_for('tree.create_tree_route') }}" class="text-blue-500 hover:underline mb-4 inline-block px-4 py-2 rounded">Create tree</a>

    </div>

    <h2 class="text-xl font-bold mb-4">Forests</h2>
    <form action="{{ url_for('forest.handle_create_forest') }}" method="post" class="mb-4 flex space-x-2" enctype="multipart/form-data">
        <input type="text" name="name" placeholder="Forest Name" class="border rounded px-4 py-2 flex-grow">
        <input type="text" name="tree_type" placeholder="Tree Type" class="border rounded px-4 py-2 flex-grow">
        <input type="file" name="image" accept="image/*" class="border rounded px-4 py-2 flex-grow">
        <button type="submit" class="bg-blue-500 text-white px-4 py-2 rounded">Create Forest</button>
    </form>

    <div class="overflow-x-auto">
        <table class="min-w-full border-collapse border border-gray-300">
            <thead class="bg-gray-100">
                <tr>
                    <th class="border border-gray-300 px-4 py-2 text-left">Forest Name</th>
                    <th class="border border-gray-300 px-4 py-2 text-left">Tree Type</th>
                    <th class="border border-gray-300 px-4 py-2 text-left">Actions</th>
                </tr>
            </thead>
            <tbody>
                {% for forest in forests.items %}
                <tr id="forest-{{ forest.id }}" class="bg-white border-b hover:bg-gray-50">
                    <td class="border border-gray-300 px-4 py-2">{{ forest.name }}</td>
                    <td class="border border-gray-300 px-4 py-2">{{ forest.tree_type }}</td>
                    <td class="border border-gray-300 px-4 py-2 space-x-2">
                        <form action="{{ url_for('forest.handle_update_forest', id=forest.id) }}" method="post" class="inline-block">
                            <input type="text" name="name" value="{{ forest.name }}" class="border rounded px-2 py-1 mr-2">
                            <input type="text" name="tree_type" value="{{ forest.tree_type }}" class="border rounded px-2 py-1 mr-2">
                            <button type="submit" class="bg-blue-500 text-white px-2 py-1 rounded">Update</button>
                        </form>
                        <form action="{{ url_for('forest.handle_delete_forest', id=forest.id) }}" method="post" class="inline-block">
                            <button type="submit" class="bg-red-500 text-white px-2 py-1 rounded">Delete</button>
                        </form>
                        <form action="{{ url_for('map.get_forest_geojson', forest_id=forest.id) }}" method="get" class="inline-block">
                            <button type="submit" class="bg-green-500 text-white px-2 py-1 rounded">View</button>
                        </form>
                        <form action="{{ url_for('map.forestReport', forest_id=forest.id) }}" method="get" class="inline-block">
                            <button type="submit" class="bg-green-500 text-white px-2 py-1 rounded">report</button>
                        </form>
                    </td>
                </tr>
                {% endfor %}
            </tbody>
        </table>
    </div>

    <!-- Pagination -->
    <div class="flex justify-center mt-8">
        {% if forests.has_prev %}
            <a href="{{ url_for('forest.index', page=forests.prev_num) }}" class="px-4 py-2 bg-gray-300 text-gray-700 rounded hover:bg-gray-400 mx-1">&laquo; Prev</a>
        {% else %}
            <span class="px-4 py-2 bg-gray-300 text-gray-700 rounded mx-1 cursor-not-allowed">&laquo; Prev</span>
        {% endif %}

        {% for page_num in forests.iter_pages() %}
            {% if page_num %}
                {% if page_num == forests.page %}
                    <span class="px-4 py-2 bg-blue-500 text-white rounded mx-1">{{ page_num }}</span>
                {% else %}
                    <a href="{{ url_for('forest.index', page=page_num) }}" class="px-4 py-2 bg-gray-300 text-gray-700 rounded hover:bg-gray-400 mx-1">{{ page_num }}</a>
                {% endif %}
            {% else %}
                <span class="px-4 py-2 mx-1">...</span>
            {% endif %}
        {% endfor %}

        {% if forests.has_next %}
            <a href="{{ url_for('forest.index', page=forests.next_num) }}" class="px-4 py-2 bg-gray-300 text-gray-700 rounded hover:bg-gray-400 mx-1">Next &raquo;</a>
        {% else %}
            <span class="px-4 py-2 bg-gray-300 text-gray-700 rounded mx-1 cursor-not-allowed">Next &raquo;</span>
        {% endif %}
    </div>

   </div>

<script>
    function editPoint(id) {
        const row = document.getElementById(`point-${id}`);
        const inputs = row.querySelectorAll('input, select');
        inputs.forEach(input => input.disabled = false);
        document.getElementById(`save-${id}`).classList.remove('hidden');
    }

    function savePoint(id) {
        const row = document.getElementById(`point-${id}`);
        const inputs = row.querySelectorAll('input, select');
        const data = {};

        inputs.forEach(input => {
            data[input.name] = input.value;
            input.disabled = true;
        });

        fetch(`/point/update/${id}`, {
            method: 'POST',
            headers: {
                'Content-Type': 'application/json'
            },
            body: JSON.stringify(data)
        }).then(response => {
            if (response.ok) {
                document.getElementById(`save-${id}`).classList.add('hidden');
            }
        });
    }
</script>
{% endblock %}